### ISSUE TITLE
Layiheye baxis

### ISSUE THREAD

**Issue by Aytac11** [Suleyman96/PragmatechFoundationProject#1]
.box un icindeki placeholder sola yapisib onu paddingle duzeldin.

![image](https://user-images.githubusercontent.com/69673205/109419567-8f173080-79e7-11eb-9a79-e429c46c3049.png)

Burada baxin asagida qeyd etdiyim kodlara gore scroll yaranib.

```
.header-navbar {
    width: 1366px;}

.navbar-container {
width: 100%;
margin: 0px 200px;}
```

![image](https://user-images.githubusercontent.com/69673205/109419629-d9001680-79e7-11eb-8dae-02d357e5370e.png)

Buradaki slider buttons ortada dayanmalidir, amma sizde yuxaridadir.

**Comment by Suleyman96** [comment]
scroll düzəltdim, buttonlar məndə ortadadı) topI: 50% vermişəm, sizdə bilmirəm niyə elə görsənib)

**Comment by Suleyman96** [comment]
Salam. Aytac xanım scroll düzəldi. Placeholder-a padding vermək olmur((
Buttonlar məndə ortada gəlib, top:50% vermişəm elə düz deyil ki?

Aytac11 <notifications@github.com>, 28 Şub 2021 Paz, 17:12 tarihinde şunu
yazdı:

**Comment by Aytac11** [comment]
He ortada olmalidir amma bilmirem mende niye ele gorunub
